DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON (
  id INT  PRIMARY KEY,
    first_name VARCHAR(250) NOT NULL,
    last_name VARCHAR(250) NOT NULL
    );

DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  id INT  PRIMARY KEY,
    username VARCHAR(250) NOT NULL,
    password VARCHAR(250) NOT NULL
    );